
# Python Foundations

> Computational Analysis of Social Complexity
>
> Fall 2025, Spencer Lyon

**Prerequisites**

- Laptop or personal computer with internet connection

**Outcomes**

- Understand the main benefits and features of Python
- See how to define variables, functions, and simple data structures in Python
- Get comfortable with numbers, strings, lists, tuples, and dictionaries

**References**

- [Python](https://docs.python.org/3/tutorial/) tutorial (official documentation)
- [NumPy](https://numpy.org/doc/stable/) documentation
- [QuantEcon Python lectures](https://python-programming.quantecon.org/intro.html)



## What is Python?

- Python is a general purpose, high level programming language first released in 1991
- It emphasizes readable, expressive syntax -- Python code often reads almost like pseudocode
- On its own Python is not the fastest language, but its massive scientific ecosystem (`numpy`, `pandas`, `scipy`, and friends) lets us write code that is both clear to read and fast to run
- It is, by a wide margin, the most popular language for data science, scientific computing, and machine learning today



## Core Types

- We'll start by learning about the core datatypes built in to Python
- Along the way we'll pick up some of the key syntax elements
- We will move quickly, so some prior programming experience would be helpful



### Numbers

- Let's start with numbers
- To work with a number, just type it!


In [1]:
42


42

- We can also do basic arithmetic in the way you would expect


In [2]:
10 * 3


30

In [3]:
1 + 2


3


- So far we've worked with integers (whole numbers)
- Python can also work with numbers containing a decimal
- In Python these are called floating point numbers (`float`)


In [4]:
1.234 ** 2.2  # use `**` for exponentiation


1.5881567008330448

In [5]:
553.34 / 12.9


42.89457364341085

- We can mix and match integers and floats


In [6]:
25 / 2.5


10.0

In [7]:
25 / 2  # dividing integers with `/` always returns a float


12.5

In [8]:
25 // 2  # `//` is floor (integer) division -- notice no decimal


12

- notice we used `#` to define a comment


## Text Data

- Not all data is numerical
- Some is textual
- To represent text in Python we use a `str`
- To define a string we can use single (`'`) or double (`"`) quotation marks -- Python treats them the same

In [9]:
"My name is Spencer"


'My name is Spencer'

In [10]:
'My name is Spencer'  # single quotes work just as well


'My name is Spencer'

In [11]:
"1"  # an integer in a string


'1'

- Triple quotes (`"""`) let a string span multiple lines


In [12]:
"""
This

is

also

a

string
"""


'\nThis\n\nis\n\nalso\n\na\n\nstring\n'

## Lists

- When doing numerical work, we often need to deal with multiple pieces of data at the same time
- In Python the default way of doing this is to use a `list`
- Lists are defined with `[` and `]` as below

In [13]:
[1, 2, 3.14]  # a 3 element list


[1, 2, 3.14]

- Plain Python lists are general purpose containers, not built for linear algebra
- For matrices and vectorized math we reach for `numpy` arrays instead

In [14]:
import numpy as np

np.array([1, 2, 3])  # a numpy array (vector)


array([1, 2, 3])

In [15]:
np.array([[1, 2, 3]])  # a 1x3 matrix


array([[1, 2, 3]])

In [16]:
np.array([[1, 2], [3, 4]])  # a 2x2 matrix


array([[1, 2],
       [3, 4]])

In [17]:
np.array([
    [1, 2],
    [3, 4],
])  # another way to write a 2x2 matrix


array([[1, 2],
       [3, 4]])


### Accessing list/array items

- We can use `[N]` to access the Nth element
- We can also use `[i:j]` to access items `i` through `j` (exclusive of `j`)
- Finally we can use fancy indexing with a list of positions to access several elements at once


In [18]:
[100, 101, 102, 103][1]


101

In [19]:
[100, 101, 102, 103][1:4]


[101, 102, 103]

In [20]:
np.array([100, 101, 102, 103])[[0, 2]]


array([100, 102])

- Note that Python starts counting at 0
- Also note that `-1` refers to the last element, `-2` to the second to last, and so on

In [21]:
[1, 2, 3, 4][-1]


4

In [22]:
[1, 2, 3, 4][-3]


2


## Tuples

- There is another data type for holding "lists" of data called a tuple
- Tuples are created using parentheses instead of square brackets as follows


In [23]:
(1, 2, 3, "hello")


(1, 2, 3, 'hello')

In [24]:
("hello", 5)


('hello', 5)

In [25]:
("hello", 5)[1]


5


- The main differences between tuples and lists are
    1. Tuples are meant to hold immutable or non-changing data (you cannot reassign an element of a tuple)
    2. Tuples aren't usually meant for computation or linear algebra



## Dictionaries

- Very often in programming we want to be able to associate a key or name to a specific value
- One data type for doing that is a `dict`
- Dicts are created with the syntax `{key: value, ...}` where the `...` means we can repeat the pattern multiple times
- The keys and values can be of any (hashable, for keys) type


In [26]:
{"x": 1, 2: "y", ("w", "z"): [1, 2, 3]}


{'x': 1, 2: 'y', ('w', 'z'): [1, 2, 3]}

In [27]:
# use `[key]` to access the element with that key
{"x": 1, 2: "y", ("w", "z"): [1, 2, 3]}[2]


'y'

In [28]:
{"x": 1, "y": 2}


{'x': 1, 'y': 2}

- Dictionaries are often used for passing around groups of parameters
- A plain `dict` with string keys is a common way to bundle a handful of named values together
- We'll see examples later on


## Variables

- Often when programming, we need to refer to the same piece of data more than once
- To do this we use a variable
- Variables are defined using an `=`, as in `name = value`


In [29]:
x = 1


In [30]:
y = 42


In [31]:
x + y  # 'use' or 'refer to' x and y


43

In [32]:
m1 = np.array([[1, 0], [0, 1]])


In [33]:
m2 = np.array([[1, 2], [3, 4]])


In [34]:
m1 @ m2  # matrix multiplication uses `@`, not `*`


array([[1, 2],
       [3, 4]])

In [35]:
m2 @ m2  # again -- but with something besides identity matrix!


array([[ 7, 10],
       [15, 22]])

In [36]:
d = {"X": 1, "Y": 2}


In [37]:
d["X"]


1


## Functions

- Most Python programs do more than basic arithmetic operations on data
- To apply an operation to a piece of data, we call a function
- To call a function we use `function_name(data1, data2)`
- A very handy function is the built in `type` function


In [38]:
type(1)


int

In [39]:
type(2.0)


float

In [40]:
type([1, 2, 3])


list

In [41]:
type(np.array([[1, 2], [3, 4.0]]))


numpy.ndarray

- Many standard operations are available as functions or methods


In [42]:
sum([1, 2, 3])  # compute sum of a list of numbers


6

In [43]:
np.linalg.inv(np.array([[1, 2], [3, 4]]))  # matrix inverse


array([[-2. ,  1. ],
       [ 1.5, -0.5]])

In [44]:
np.array([[1, 2], [3, 4]]).shape  # (rows, columns) in the array


(2, 2)

In [45]:
len([1, 2, 3])  # number of elements in a list


3

In [46]:
np.array([[1, 2], [3, 4]]).size  # returns total number of elements in an array


4

In [47]:
np.random.rand(2, 2, 2)  # a 2x2x2 array of random numbers, sampled from uniform[0,1] dist


array([[[0.88479025, 0.78550034],
        [0.89388256, 0.07210416]],

       [[0.79807596, 0.9551588 ],
        [0.49565154, 0.35452377]]])


- Python's standard library, plus `numpy`/`pandas`/`scipy`, gives us thousands of functions
- We'll learn more as we go along...
- Just watch for the pattern with parentheses: `name(args)`



### Defining Functions

- Functions are used to execute a predefined set of operations
- Defining our own functions allows us to break programs into small, easily written and understood components
- We define functions using the syntax
```python
def name(arg1, arg2):
    # steps
    return result
```


In [48]:
def mean(x):
    total = sum(x)
    n = len(x)
    return total / n


In [49]:
mean([1, 2, 3])


2.0

In [50]:
# mean of 1000 random samples from U[0,1] -- should be ~ 0.5
mean(np.random.rand(1000))


np.float64(0.4864274563302127)


- If a function only contains one expression, you can also use a `lambda` (Python's anonymous-function shorthand):
```python
function_name = lambda arg1, arg2: # step
```


In [51]:
add_two = lambda x: x + 2


In [52]:
add_two(40)


42


## Getting help for functions

- Given that there are so many functions, sometimes it is hard to remember exactly what a function does
- Thankfully we can get help right inside Python
- If we call `help(function_name)`, or in Jupyter/IPython type `function_name?`, we get documentation about the function


In [53]:
help(map)


Help on class map in module builtins:

class map(object)
 |  map(func, *iterables) --> map object
 |
 |  Make an iterator that computes the function using arguments from
 |  each of the iterables.  Stops when the shortest iterable is exhausted.
 |
 |  Methods defined here:
 |
 |  __getattribute__(self, name, /)
 |      Return getattr(self, name).
 |
 |  __iter__(self, /)
 |      Implement iter(self).
 |
 |  __next__(self, /)
 |      Implement next(self).
 |
 |  __reduce__(...)
 |      Return state information for pickling.
 |
 |  ----------------------------------------------------------------------
 |  Static methods defined here:
 |
 |  __new__(*args, **kwargs)
 |      Create and return a new object.  See help(type) for accurate signature.



In [54]:
sorted?



## Control Flow

- Python has the basic elements of control flow:
    - `if`-`elif`-`else` statements
    - `for` loops


In [55]:
if 1 > 2:  # no parenthesis needed, but the colon and indentation matter
    print("what???")
else:      # else is optional
    print(mean([1, 2, 3]))


2.0


In [56]:
for i in range(1, 6):  # range of numbers 1 to 5
    print(i, i ** 2)


1 1
2 4
3 9
4 16
5 25


- We will see many more examples as we go forward



## Comprehensions

- Python has a compact syntax -- the *comprehension* -- for building a list (or dict, or set) out of a loop and an expression
- A comprehension `[expr for item in iterable]` is equivalent to (but often faster than) building up a list with a `for` loop and `.append`


In [57]:
[i ** 2 for i in range(1, 6)]  # squares of 1 through 5


[1, 4, 9, 16, 25]

In [58]:
[i for i in range(20) if i % 3 == 0]  # comprehensions can filter with `if`


[0, 3, 6, 9, 12, 15, 18]

In [59]:
{i: i ** 2 for i in range(5)}  # dict comprehension


{0: 0, 1: 1, 2: 4, 3: 9, 4: 16}

In [60]:
np.array([i ** 2 for i in range(1, 6)])  # wrap in np.array for vectorized follow-up math


array([ 1,  4,  9, 16, 25])